UserRolesExample/Areas/Admin/Controllers/RolesManagerController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace UserRolesExample.Areas.Admin.Controllers
{
    [Authorize(Roles = "SuperAdmin")]
    [Area("Admin")]
    public class RolesManagerController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;

        public RolesManagerController(RoleManager<IdentityRole> roleManager)
        {
            _roleManager = roleManager;
        }
        public async  Task<IActionResult> Index()
        { 
            return View(await _roleManager.Roles.ToListAsync());
        }

        [HttpPost]
        public async Task<IActionResult> AddRole(string roleName)
        {
            if (roleName != null)
            {
                await _roleManager.CreateAsync(new IdentityRole(roleName.Trim()));
            }

            return RedirectToAction("Index");
        }
    }
}

UserRolesExample/Areas/Admin/Views/RolesManager/Index.cshtml
@model IEnumerable<Microsoft.AspNetCore.Identity.IdentityRole>

@{
    ViewData["Title"] = "Roles Manager";
}


<form method="post" asp-action="AddRole" asp-controller="RolesManager">
    <div class="input-group">
        <input name="roleName" class="form-control w-25" />
        <span class="input-group-btn">
            <button class="btn btn-info">Add New Role</button>
        </span>
    </div>
</form>

<table class="table table-striped">
    <thead class="thead-dark">
        <tr>ID</tr>
        <tr>Role</tr>
    </thead>
    <tbody>
        @foreach (var role in Model)
        {
            <tr>
                <td>@role.Id</td>
                <td>@role.Name</td>
            </tr>
        }
    </tbody>
</table>